# Generated by Django 2.0.13 on 2019-07-07 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Ubicacion', models.CharField(max_length=200)),
                ('ZipCode', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Hora', models.CharField(max_length=100)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
