# Generated by Django 2.0.13 on 2019-07-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aires_acondicionados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='Hora',
        ),
    ]
